framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
        save_path: '%kernel.cache_dir%%/sessions'

    php_errors:
        log: true
