security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: lazy
            provider: database_users
