parameters:
    default_email_from: '%env(DEFAULT_EMAIL_FROM)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\EventListener\LikeNotificationSubscriber:
        tags:
            - {
                  name: doctrine.event_subscriber
                  connection: default
            }

    App\Mailer\Mailer:
        arguments:
            $defaultEmailFrom: '%default_email_from%'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%env(DATABASE_URL)%'
